### PR TITLE
feat: Add 'expo' and 'gradle' folders

### PR DESCRIPTION
**Pull request by Pedroo-Nietoo**
## What does this PR add to the project?
This commit adds two new folders to the extension: the `expo` and `gradle` folders.

The Figma file with the new folders can be found by clicking [here](https://www.figma.com/design/SSZ9bDvjTSvXiUvZcAxGOF/Symbols---File-Icons-(Copy)?node-id=20521-84115&t=SAMWL3cnqXIP8S8a-1).

## Print with the icons working
image

### CODE REVIEW

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
Thanks for the PR, it looks like the expo icon does not look good in dark themes. Can you update the color to use one of the other gray colors from other icons (github, next, etc.)? Those tend to work better in dark/light themes.

**Comment by Pedroo-Nietoo** [comment]
Sure! I'll update it and upload it again.

**Comment by miguelsolorio** [comment]
Much better, thank you!

**Comment by Pedroo-Nietoo** [comment]
Good afternoon miguelsolorio, how are you?

I would like to know, if it weren't too much trouble, how often the project is updated. I really like this extension and I am very interested in joining as a contributor to the project!

**Review by miguelsolorio — APPROVED** [review]

**Pull request merged**
