### PR TITLE
Add icon/folder-icon for Gitlab

### PR DESCRIPTION
**Pull request by dimentoree**
Add icon and folder-icon for `GitLab` files

изображение
изображение

### CODE REVIEW

**Comment by miguelsolorio** [comment]
@dimentoree had to fix the icon size because it was too large, also what is the file name for a gitlab issue? Can't seem to find any info on `.gitlab-issues`

CleanShot 2024-09-03 at 22 56 48@2x

**Comment by dimentoree** [comment]
> @dimentoree had to fix the icon size because it was too large, also what is the file name for a gitlab issue? Can't seem to find any info on `.gitlab-issues`
> 
> CleanShot 2024-09-03 at 22 56 48@2x

Hi, regarding the file name `.gitlab-issues` - I specified it at first by analogy with git, but when I started checking what file types are used with gitlab, I didn't find one and probably forgot to remove it. I'll be more careful in the future, thanks

**Comment by miguelsolorio** [comment]
This PR was a little gnarly so I had to add this separately in https://github.com/miguelsolorio/vscode-symbols/commit/25b8199925f522e3b8fadbd8bf8a30e57e68d891 I'll still credit you in the release notes

**Comment by dimentoree** [comment]
> This PR was a little gnarly with the previous commits, so I had to add this separately in [25b8199](https://github.com/miguelsolorio/vscode-symbols/commit/25b8199925f522e3b8fadbd8bf8a30e57e68d891) I'll still credit you in the release notes

Thank you very much)

**Pull request closed without merging**
