### PR TITLE
Add folder and file to .test.ts and .spec.ts from Typescript

### LINKED ISSUE #203: Add folder file .test.ts and .spec.ts from Typescript
Screenshot 2024-04-21 183726

@miguelsolorio 
link figma:
https://www.figma.com/file/UQQzTjcRvWsZW9udePXOSr/Symbols---File-Icons-(Copy)?type=design&node-id=20521%3A84115&mode=design&t=cxpeBsDKfucJQq5G-1

### PR DESCRIPTION
**Pull request by the-spanish-guy**
# Description
- update ts-test file icons
- add folder-test icon

# Issue
Resolves #203 

# Preview
image

### CODE REVIEW

**Comment by castrogarciajs** [comment]
I think it would just be changing the folder, I really like the way .spec and .test look now with that orange color.

What do you think @miguelsolorio?

**Comment by miguelsolorio** [comment]
I'm not a big fan of the more graphical test tube, most of the theme is singular lines. If you could provide some alternative examples that would be great otherwise I'm happy to design some.

**Comment by castrogarciajs** [comment]
I agree with you. Maybe we should use folder green or folder red for folders *tests*. But They are only suggestions, I will send a PR with the idea and tell me what you think.

**Comment by the-spanish-guy** [comment]
> I think it would just be changing the folder, I really like the way .spec and .test look now with that orange color.
> 
> What do you think @miguelsolorio?

I like how the folders look with the new icons, I believe that for file icons it is not necessary but for folders I like how they differ from other folders

**Comment by miguelsolorio** [comment]
I would also only add this for folders, files already have an existing pattern of using blue = source and orange = test from previous file icon themes so I'd like to keep to that.

**Comment by the-spanish-guy** [comment]
I will revert the file icons and keep the changes to the folder icons

**Comment by the-spanish-guy** [comment]
@miguelsolorio I updated the description with an image showing the result

**Comment by miguelsolorio** [comment]
@the-spanish-guy I think you may have missed my original comment about not being a fan of the 3D test tubes, can you provide some different options that fit with the rest of the theme? Otherwise I am happy to add one and close this PR.

**Pull request closed without merging**
