### PR TITLE
add "hooks" and "constants" folders

### PR DESCRIPTION
**Pull request by iJuulia**

### CODE REVIEW

**Comment by sebastiandotdev** [comment]
Hello @iJuulia,

I think you need to add the `folder-hooks` and `folder-constants` icon to the `“iconDefinitions”: { }` object.

**Comment by sebastiandotdev** [comment]
@miguelsolorio I support the idea of the icons, it seems to me that it goes according to the design that you manage.

**Comment by iJuulia** [comment]
You are right, thanks for pointing that out. I fixed it :)

**Comment by miguelsolorio** [comment]
@iJuulia thanks for the PR, please add a screenshot of the extension running with these new additions. Thanks.

**Review by miguelsolorio — APPROVED** [review]
CleanShot 2024-10-25 at 14 46 38@2x

Made some minor color and size changes, also fixed some broken paths. Please ensure you test this locally next time and attach a screenshot. Thanks!

**Pull request merged**
