### PR TITLE
Add NestJS Guard, Decorator icons

### PR DESCRIPTION
**Pull request by premdasvm**
Changes made:

1. Decorator icon - `nest-decorator.svg`
2. Middleware icon - `nest-middleware.svg`

to use: 

```json
  "symbols.files.associations": {
    "*.decorator.ts": "nest-decorator",
    "*.middleware.ts": "nest-middleware"
  }
  ```
  
CleanShot 2024-11-30 at 22 24 15@2x

### CODE REVIEW

**Comment by FabianMontoya** [comment]
It would be nice If you could add the other nestjs-files variants

image

**Comment by premdasvm** [comment]
@FabianMontoya Will do, i was planning to do it already.

**Comment by FabianMontoya** [comment]
> @FabianMontoya Will do, i was planning to do it already.

Thank u for the work!

**Review by miguelsolorio — APPROVED** [review]
🫶 LGTM, thanks for the PR!

**Pull request merged**
