### PR TITLE
Add some icons for `Angular` files

### PR DESCRIPTION
**Pull request by dimentoree**
Add icons for:
- directive files
- module files
- guard files
- pipe files

Also add icon support for `service.dart` and `component.dart` files

### CODE REVIEW

**Comment by miguelsolorio** [comment]
@dimentoree thanks for the PR, can you add a screenshot of these icons from the extension? Thanks!

**Comment by dimentoree** [comment]
> @dimentoree thanks for the PR, can you add a screenshot of these icons from the extension? Thanks!

Miguel, can you explain how to correctly add the display of new icons for files in the VS code, because I can’t seem to get it right? And then attaching screenshots of icons from Figma is so-so

**Comment by miguelsolorio** [comment]
@dimentoree I'm not sure I understand your question. Are you asking how to new file icons? You've created PRs before so this question is a little confusing.

**Comment by dimentoree** [comment]
> @dimentoree I'm not sure I understand your question. Are you asking how to add new file icons? You've created PRs before so this question is a little confusing.

Hi, sorry for the long absence. I figured out my problem, so the issue is resolved. I am attaching a screenshot
изображение

**Review by miguelsolorio — APPROVED** [review]

**Pull request merged**
