### PR TITLE
update deno icon

### PR DESCRIPTION
**Pull request by falcao-g**
updates the deno icon to the newly icon made for version 2

### CODE REVIEW

**Comment by miguelsolorio** [comment]
@falcao-g Thanks for the PR, can you please add a screenshot of the extension running with this update? I suspect a black icon on a dark theme will not be very visible. Thanks.

**Comment by falcao-g** [comment]
hey, of course, here is a image of how it looks, my theme is not *that* dark (more like purple lol), but it looks fine here

image

**Review by Vinicius-Marques6 — COMMENTED** [review]
Perhaps switching to the same color palette as the old icon would be a good idea.

Another thing is that the size of the icon is different from the previous one.

My suggestion is:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M12.465,2.011c5.513.256,9.781,4.941,9.524,10.454s-4.941,9.781-10.454,9.524c-5.513-.256-9.781-4.941-9.524-10.454S6.952,1.755,12.465,2.011ZM14.803,14.052c-.631-.031-1.254-.137-1.755-.22-.381-.064-.742-.164-1.039-.266-.048-.017-.102-.001-.133.04-.031.041-.035.101,0,.139.14.155.584.479.929.628-.295.244-.497.8-.576,1.089-.107.387-.122.945-.096,1.151.104.825.407,1.564,1.158,2.211.526.453,1.286.762,2.064.776,1.073.019,2.358-.442,3.367-1.478,1.319-1.446,2.183-3.326,2.344-5.427.382-5.003-3.369-9.374-8.372-9.756-5.003-.382-9.374,3.369-9.756,8.372-.198,2.591.713,5.012,2.332,6.798.045.049.118.061.176.029.058-.032.087-.1.07-.164-1.201-4.703,1.404-9.78,4.312-11.387,1.079-.597,2.131-.823,3.075-.441,1.446.585,2.273,1.554,4.063,2.37,1.79.815,1.984,2.175,1.485,3.549s-2.107,2.065-3.646,1.99ZM11.671,6.777c-.587.046-.972.772-1.022,1.239-.051.467.181,1.238.945,1.223.895-.018,1.167-.784,1.069-1.525-.074-.557-.502-.975-.992-.937Z" fill="#2563EB"/>
</svg>
```

new deno icon preview

**Comment by miguelsolorio** [comment]
@Vinicius-Marques6 the new branding does not use the blue color anymore https://deno.com/blog/v2.0

**Comment by Vinicius-Marques6** [comment]
I understand, but searching the internet I didn't find any occurrence of the logo having been blue at some point, the comparison would be with the logo that is currently used in the extension. The only thing I found was the PR from when the old logo was created (https://github.com/denoland/dotland/pull/1836).

**Comment by sebastiandotdev** [comment]
@miguelsolorio In vscode is there a way to detect when the user has dark theme colors?. Here is an example of changing the deno.land page to dark mode.

### Preview

Captura de pantalla 2024-10-15 a la(s) 3 10 15 p m

**Comment by miguelsolorio** [comment]
just getting around to previewing this, and I think this is why we went with blue was because the theme is used for both dark and light. So this is what it looks like in a light theme:

CleanShot 2024-10-23 at 10 42 14@2x

We can update the color to use a neutral gray that works in both:

CleanShot 2024-10-23 at 10 47 55@2x
CleanShot 2024-10-23 at 10 48 50@2x

If others feel strongly about the blue, happy to introduce a new variant that folks can override in their settings.

**Comment by falcao-g** [comment]
the gray one looks good to me

**Comment by Vinicius-Marques6** [comment]
LGTM 👍

**Review by miguelsolorio — APPROVED** [review]

**Pull request merged**
