### PR TITLE
Add icon to luau files 

### PR DESCRIPTION
**Pull request by zoi1op**
**Hello, please add luau language icon.**
 
https://luau.org/ -- link

### CODE REVIEW

**Comment by miguelsolorio** [comment]
Thanks for the PR, do you mind adding a screenshot to your PR? Thanks!

**Review by zoi1op — COMMENTED** [review]
edited files

**Comment by zoi1op** [comment]
image

**Review by miguelsolorio — APPROVED** [review]
CleanShot 2024-10-24 at 16 37 06@2x

**Pull request merged**
