### PR TITLE
Add icon to fortran files

### PR DESCRIPTION
**Pull request by GabLunaDev**
I've added an icon for fortran related files

### CODE REVIEW

**Comment by miguelsolorio** [comment]
@GabLunaDev Thanks for the PR, do you mind adding a screenshot to your PR? Thanks!

**Comment by GabLunaDev** [comment]
Sure! Here is the screenshot.
fortran-screeshot

**Comment by miguelsolorio** [comment]
Can you update the icon to be a little smaller (to match the others) and using the same type of colors from the theme? [Contributing instructions](https://github.com/miguelsolorio/vscode-symbols?tab=readme-ov-file#contributing) for reference. It would also be great to see a better example of these files in a sample project to see how the others fit. Thanks!

**Review by miguelsolorio — APPROVED** [review]
CleanShot 2024-10-24 at 16 30 16@2x

**Pull request merged**
